-- Add comprehensive lessons for the new training courses (using specific course IDs to avoid duplicates)
INSERT INTO public.lessons (course_id, title, description, content, order_index, duration_minutes) VALUES

-- Find and use the latest course IDs for lessons
-- Essential Knife Skills Mastery lessons (using the most recent one)
((SELECT id FROM courses WHERE title = 'Essential Knife Skills Mastery' ORDER BY created_at DESC LIMIT 1), 'Knife Safety & Selection', 'Learn proper knife handling, safety protocols, and how to choose the right knife for each task', '{"video_url": "https://www.youtube.com/watch?v=JMA2SqaDgG8", "overview": "Master the fundamentals of knife safety and selection", "transcript": "Welcome to knife safety fundamentals...", "resources": ["Knife safety checklist", "Knife selection guide"], "quiz": [{"question": "What is the most important rule of knife safety?", "options": ["Keep knives sharp", "Always cut away from yourself", "Store knives properly", "All of the above"], "correct": 3}]}', 1, 45),

((SELECT id FROM courses WHERE title = 'Essential Knife Skills Mastery' ORDER BY created_at DESC LIMIT 1), 'Basic Knife Cuts', 'Master the fundamental cuts: brunoise, julienne, chiffonade, and dice', '{"video_url": "https://www.youtube.com/watch?v=G-Fg7l7G1zw", "overview": "Learn the classic French knife cuts essential for professional cooking", "transcript": "Today we will master the fundamental cuts...", "resources": ["Knife cut reference chart", "Practice exercises"], "quiz": [{"question": "What size is a small dice (brunoise)?", "options": ["1/8 inch", "1/4 inch", "1/2 inch", "1 inch"], "correct": 0}]}', 2, 60),

((SELECT id FROM courses WHERE title = 'Essential Knife Skills Mastery' ORDER BY created_at DESC LIMIT 1), 'Advanced Knife Techniques', 'Learn professional techniques like filleting, boning, and carving', '{"video_url": "https://www.youtube.com/watch?v=nffGuGwCdZE", "overview": "Master advanced knife work for professional kitchens", "transcript": "Advanced techniques require precision and practice...", "resources": ["Filleting guide", "Carving techniques"], "quiz": [{"question": "When filleting fish, which direction should you cut?", "options": ["Against the grain", "With the grain", "Perpendicular to spine", "Parallel to spine"], "correct": 2}]}', 3, 75),

-- Professional Baking Techniques lessons
((SELECT id FROM courses WHERE title = 'Professional Baking Techniques' ORDER BY created_at DESC LIMIT 1), 'Bread Making Fundamentals', 'Understanding yeast, gluten development, and basic bread techniques', '{"video_url": "https://www.youtube.com/watch?v=tejAykMAF78", "overview": "Learn the science behind bread making", "transcript": "Bread making is both art and science...", "resources": ["Yeast conversion chart", "Bread troubleshooting guide"], "quiz": [{"question": "What temperature kills yeast?", "options": ["100°F", "120°F", "140°F", "160°F"], "correct": 2}]}', 1, 90),

((SELECT id FROM courses WHERE title = 'Professional Baking Techniques' ORDER BY created_at DESC LIMIT 1), 'Pastry Dough Techniques', 'Master pie crust, puff pastry, and choux pastry fundamentals', '{"video_url": "https://www.youtube.com/watch?v=Ki_9xz-nLks", "overview": "Learn to create perfect pastry doughs", "transcript": "Pastry requires precision and temperature control...", "resources": ["Pastry temperature guide", "Troubleshooting tips"], "quiz": [{"question": "What creates layers in puff pastry?", "options": ["Eggs", "Steam", "Baking powder", "Sugar"], "correct": 1}]}', 2, 85),

-- Food Plating & Presentation Mastery lessons
((SELECT id FROM courses WHERE title = 'Food Plating & Presentation Mastery' ORDER BY created_at DESC LIMIT 1), 'Plating Principles & Techniques', 'Learn the fundamentals of visual composition and plate design', '{"video_url": "https://www.youtube.com/watch?v=ALbE5dGmUgc", "overview": "Master the art of food presentation", "transcript": "Great plating starts with understanding visual principles...", "resources": ["Plating technique guide", "Color wheel for chefs"], "quiz": [{"question": "What is the rule of thirds in plating?", "options": ["Use three colors", "Divide plate into thirds", "Three textures", "Three temperatures"], "correct": 1}]}', 1, 50),

((SELECT id FROM courses WHERE title = 'Food Plating & Presentation Mastery' ORDER BY created_at DESC LIMIT 1), 'Sauce Work & Garnishing', 'Master sauce application and creative garnishing techniques', '{"video_url": "https://www.youtube.com/watch?v=_WlFPEanpuI", "overview": "Learn professional sauce and garnish techniques", "transcript": "Sauces and garnishes complete the visual story...", "resources": ["Sauce consistency guide", "Garnish ideas"], "quiz": [{"question": "What tool is best for precise sauce dots?", "options": ["Spoon", "Squeeze bottle", "Brush", "Offset spatula"], "correct": 1}]}', 2, 45),

-- Restaurant Cost Control & Food Costing lessons
((SELECT id FROM courses WHERE title = 'Restaurant Cost Control & Food Costing' ORDER BY created_at DESC LIMIT 1), 'Food Cost Calculations', 'Learn to calculate food costs, portions, and recipe costing', '{"video_url": "https://www.youtube.com/watch?v=texample", "overview": "Master the mathematics of food costing", "transcript": "Understanding food costs is crucial for profitability...", "resources": ["Food cost calculator", "Portion control guide"], "quiz": [{"question": "What should food costs typically be as a percentage of sales?", "options": ["15-20%", "25-35%", "40-50%", "55-65%"], "correct": 1}]}', 1, 60),

((SELECT id FROM courses WHERE title = 'Restaurant Cost Control & Food Costing' ORDER BY created_at DESC LIMIT 1), 'Portion Control Systems', 'Implement effective portion control and waste reduction strategies', '{"video_url": "https://www.youtube.com/watch?v=texample2", "overview": "Learn systems for consistent portioning", "transcript": "Consistent portions ensure consistent profits...", "resources": ["Portion tools guide", "Waste tracking sheet"], "quiz": [{"question": "Why is portion control important?", "options": ["Consistency", "Cost control", "Customer satisfaction", "All of the above"], "correct": 3}]}', 2, 45),

-- Professional Wine Service & Pairing lessons
((SELECT id FROM courses WHERE title = 'Professional Wine Service & Pairing' ORDER BY created_at DESC LIMIT 1), 'Wine Service Fundamentals', 'Learn proper wine service techniques and etiquette', '{"video_url": "https://www.youtube.com/watch?v=texample3", "overview": "Master professional wine service", "transcript": "Wine service is a choreographed performance...", "resources": ["Wine service checklist", "Glassware guide"], "quiz": [{"question": "At what temperature should red wine typically be served?", "options": ["45-50°F", "55-60°F", "62-68°F", "70-75°F"], "correct": 2}]}', 1, 55),

-- Kitchen Leadership & Team Management lessons
((SELECT id FROM courses WHERE title = 'Kitchen Leadership & Team Management' ORDER BY created_at DESC LIMIT 1), 'Leadership in High-Pressure Environments', 'Develop leadership skills for busy kitchen operations', '{"video_url": "https://www.youtube.com/watch?v=texample5", "overview": "Lead effectively during service rushes", "transcript": "Kitchen leadership requires calm under pressure...", "resources": ["Leadership assessment", "Communication strategies"], "quiz": [{"question": "What is the most important quality in kitchen leadership?", "options": ["Technical skill", "Clear communication", "Speed", "Authority"], "correct": 1}]}', 1, 70),

-- Allergen Management lessons
((SELECT id FROM courses WHERE title = 'Allergen Management in Professional Kitchens' ORDER BY created_at DESC LIMIT 1), 'Common Food Allergens', 'Identify and understand the top food allergens and cross-contamination risks', '{"video_url": "https://www.youtube.com/watch?v=texample7", "overview": "Master allergen identification and management", "transcript": "Allergen management can save lives...", "resources": ["Allergen chart", "Cross-contamination prevention"], "quiz": [{"question": "How many major allergens are there?", "options": ["6", "8", "9", "14"], "correct": 2}]}', 1, 40),

-- Sustainable Cooking lessons
((SELECT id FROM courses WHERE title = 'Sustainable Cooking & Waste Reduction' ORDER BY created_at DESC LIMIT 1), 'Zero Waste Kitchen Techniques', 'Learn to minimize food waste through better planning and utilization', '{"video_url": "https://www.youtube.com/watch?v=texample9", "overview": "Create a zero-waste kitchen operation", "transcript": "Every scrap has potential...", "resources": ["Waste audit sheet", "Utilization ideas"], "quiz": [{"question": "What percentage of food is typically wasted in restaurants?", "options": ["10-15%", "20-25%", "30-40%", "45-50%"], "correct": 2}]}', 1, 50),

-- Asian Culinary Techniques lessons
((SELECT id FROM courses WHERE title = 'Asian Culinary Techniques' ORDER BY created_at DESC LIMIT 1), 'Wok Cooking Mastery', 'Master the techniques of wok cooking and stir-frying', '{"video_url": "https://www.youtube.com/watch?v=texample10", "overview": "Learn authentic wok techniques", "transcript": "The wok is the heart of Asian cooking...", "resources": ["Wok seasoning guide", "Stir-fry timing chart"], "quiz": [{"question": "What is wok hei?", "options": ["Wok smell", "Breath of the wok", "Wok temperature", "Wok technique"], "correct": 1}]}', 1, 55);