-- Add comprehensive Square POS training courses
INSERT INTO courses (title, description, instructor_name, difficulty_level, duration_hours, category, tags, is_featured) VALUES
  ('Square Fundamentals: Complete Setup Guide', 'Master Square POS setup from account creation to first sale. Learn hardware connection, payment processing basics, and essential navigation.', 'Sarah Chen', 'beginner', 2, 'pos-square', ARRAY['setup', 'basics', 'payments', 'hardware'], true),
  ('Square Payment Processing Mastery', 'Deep dive into Square''s payment ecosystem including card processing, contactless payments, digital wallets, and payment security best practices.', 'Michael Rodriguez', 'intermediate', 3, 'pos-square', ARRAY['payments', 'security', 'contactless', 'wallets'], true),
  ('Square Inventory Management Pro', 'Complete inventory system training covering product catalogs, variants, modifiers, stock tracking, and automated purchase orders.', 'Jennifer Taylor', 'intermediate', 4, 'pos-square', ARRAY['inventory', 'products', 'tracking', 'automation'], false),
  ('Square Customer & Loyalty Programs', 'Build customer relationships with Square''s CRM tools, loyalty programs, marketing campaigns, and customer insights analytics.', 'David Kim', 'intermediate', 3, 'pos-square', ARRAY['customers', 'loyalty', 'marketing', 'crm'], false),
  ('Square Analytics & Business Intelligence', 'Transform your business with Square''s reporting suite. Learn sales analysis, performance metrics, trend identification, and custom dashboards.', 'Lisa Thompson', 'advanced', 4, 'pos-square', ARRAY['analytics', 'reporting', 'business-intelligence', 'kpi'], true),
  ('Square API Development & Integrations', 'Advanced course for developers and power users. Master Square APIs, webhooks, third-party integrations, and custom solutions.', 'Alex Johnson', 'advanced', 5, 'pos-square', ARRAY['api', 'development', 'integrations', 'webhooks'], false),
  ('Square Multi-Location Management', 'Scale your business across multiple locations with centralized management, location-specific reporting, and unified inventory control.', 'Maria Gonzalez', 'advanced', 3, 'pos-square', ARRAY['multi-location', 'scaling', 'management', 'enterprise'], false),
  ('Square E-commerce Integration', 'Seamlessly connect online and offline sales with Square''s omnichannel capabilities, website integration, and inventory synchronization.', 'Robert Clark', 'intermediate', 3, 'pos-square', ARRAY['ecommerce', 'omnichannel', 'online', 'integration'], false);

-- Add comprehensive Toast POS training courses
INSERT INTO courses (title, description, instructor_name, difficulty_level, duration_hours, category, tags, is_featured) VALUES
  ('Toast Platform Fundamentals', 'Complete introduction to Toast''s restaurant-focused ecosystem. Learn basic POS operations, menu setup, and hardware configuration.', 'Chef Marcus Williams', 'beginner', 3, 'pos-toast', ARRAY['fundamentals', 'restaurant', 'menu', 'setup'], true),
  ('Toast Menu Engineering & Optimization', 'Master menu design principles, item profitability analysis, modifier management, and dynamic pricing strategies for maximum revenue.', 'Isabella Rodriguez', 'intermediate', 4, 'pos-toast', ARRAY['menu-engineering', 'pricing', 'profitability', 'modifiers'], true),
  ('Toast Kitchen Display Systems Expert', 'Optimize kitchen operations with Toast KDS. Learn order flow management, prep time tracking, and kitchen efficiency metrics.', 'James Chen', 'intermediate', 5, 'pos-toast', ARRAY['kds', 'kitchen', 'operations', 'efficiency'], true),
  ('Toast Online Ordering & Delivery', 'Build your digital presence with Toast''s online ordering platform, delivery management, and third-party integration strategies.', 'Sofia Martinez', 'intermediate', 4, 'pos-toast', ARRAY['online-ordering', 'delivery', 'digital', 'logistics'], false),
  ('Toast Staff & Labor Management', 'Complete workforce management including employee onboarding, schedule optimization, payroll integration, and performance tracking.', 'Daniel Thompson', 'intermediate', 6, 'pos-toast', ARRAY['staff', 'labor', 'scheduling', 'payroll'], false),
  ('Toast Advanced Analytics & Growth', 'Leverage Toast''s restaurant analytics for financial reporting, customer insights, marketing automation, and growth strategies.', 'Rachel Park', 'advanced', 5, 'pos-toast', ARRAY['analytics', 'growth', 'marketing', 'insights'], true),
  ('Toast Multi-Location & Franchise Management', 'Scale restaurant operations across multiple locations with centralized reporting, brand consistency, and franchise-specific tools.', 'Kevin O''Brien', 'advanced', 4, 'pos-toast', ARRAY['multi-location', 'franchise', 'scaling', 'reporting'], false),
  ('Toast Integration & Third-Party Apps', 'Maximize Toast''s potential with integrations including delivery platforms, accounting software, loyalty programs, and custom solutions.', 'Amanda Foster', 'advanced', 3, 'pos-toast', ARRAY['integrations', 'third-party', 'apis', 'customization'], false),
  ('Toast Capital & Financial Services', 'Understand Toast''s financing options, cash advances, equipment financing, and financial planning tools for restaurant growth.', 'Christopher Lee', 'intermediate', 2, 'pos-toast', ARRAY['financing', 'capital', 'equipment', 'growth'], false),
  ('Toast Marketing & Customer Engagement', 'Build customer loyalty with Toast''s marketing suite including email campaigns, loyalty programs, and customer data utilization.', 'Nicole Davis', 'intermediate', 3, 'pos-toast', ARRAY['marketing', 'loyalty', 'engagement', 'campaigns'], false);