// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfpnnlkjqpphstpcmcsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcG5ubGtqcXBwaHN0cGNtY3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzQ2NTksImV4cCI6MjA3MjE1MDY1OX0.zLnIk-a1OAdl5e4KWSz774UqL2d51i-7Z2wd_rLxdOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});